// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsbsccujvvzrbautzoag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzYnNjY3VqdnZ6cmJhdXR6b2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzUyMzYsImV4cCI6MjA2MDkxMTIzNn0.W1YfwrFdvu4VvCTvt-CZkfyzd8KYOQIMVhKaeMap5GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);